In [44]:
import pandas as pd
from pandas import Series
import re
from cdc_ml.config import EXTERNAL_DATA_DIR
from cdc_ml.dataset.pseudo.pseudo import clean_df
from cdc_ml.dataset.constants import TIMESLOTS,TIMEZONE

In [45]:
df = pd.read_excel(EXTERNAL_DATA_DIR/"pseudo_bookings.xlsx")

In [46]:
df.head()

    name lesson_date lesson_time booking date booking time  type_of_booking
0  anmol  2025-12-04    16:25:00   2025-12-04     14:31:00                1
1  anmol  2025-12-04    16:25:00   2025-12-04     14:49:00                1
2  anmol  2025-12-04    16:25:00   2025-12-04     14:51:00                1
3  anmol  2025-12-04    16:25:00   2025-12-04     14:53:00                1
4  anmol  2025-12-04    16:25:00   2025-12-04     14:56:00                1

In [47]:
df = clean_df(df)

In [48]:
df.head()

,name,lesson_date,lesson_time,booking date,booking time,type_of_booking,lesson_timestamp,booking_timestamp
0,anmol,2025-12-04,16:25:00,2025-12-04,14:31:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:31:00+08:00
1,anmol,2025-12-04,16:25:00,2025-12-04,14:49:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:49:00+08:00
2,anmol,2025-12-04,16:25:00,2025-12-04,14:51:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:51:00+08:00
3,anmol,2025-12-04,16:25:00,2025-12-04,14:53:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:53:00+08:00
4,anmol,2025-12-04,16:25:00,2025-12-04,14:56:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:56:00+08:00

In [49]:
df.head()

,name,lesson_date,lesson_time,booking date,booking time,type_of_booking,lesson_timestamp,booking_timestamp
0,anmol,2025-12-04,16:25:00,2025-12-04,14:31:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:31:00+08:00
1,anmol,2025-12-04,16:25:00,2025-12-04,14:49:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:49:00+08:00
2,anmol,2025-12-04,16:25:00,2025-12-04,14:51:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:51:00+08:00
3,anmol,2025-12-04,16:25:00,2025-12-04,14:53:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:53:00+08:00
4,anmol,2025-12-04,16:25:00,2025-12-04,14:56:00,1,2025-12-04 16:25:00+08:00,2025-12-04 14:56:00+08:00