In [1]:
import pandas as pd
from cdc_ml.config import INTERIM_DATA_DIR,RAW_DATA_DIR
from cdc_ml.datasets.records_pseudo.records_pseudo import merge_df

2026-05-06 20:33:59.138 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_records = pd.read_parquet(INTERIM_DATA_DIR/"records.parquet")
df_pseudo = pd.read_parquet(INTERIM_DATA_DIR/"pseudo.parquet")

In [3]:
df_records.head()

,id,username,booking,created_at,lesson_at,booking_at
0,60,ajithak,"Date: 2025-08-28 , Time: 18:50 - 20:30",2025-08-21 01:24:06.300383+00:00,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00
1,61,ajithak,"Date: 2025-08-28 , Time: 20:40 - 22:20",2025-08-21 01:24:16.048708+00:00,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00
2,62,addity,"Date: 2025-09-21 , Time: 14:35 - 16:15",2025-08-22 16:57:26.576198+00:00,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00
3,63,bryan,"Date: 2025-08-28 , Time: 20:40 - 22:20",2025-08-25 04:06:06.539664+00:00,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00
4,73,bryan,"Date: 2025-08-31 , Time: 12:45 - 14:25",2025-08-26 04:50:24.317931+00:00,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00

In [4]:
df_pseudo.head()

,name,lesson_date,lesson_time,booking date,booking time,type_of_booking,id,lesson_at,booking_at
0,anmol,2025-12-04,16:25:00,2025-12-04,14:31:00,1,0,2025-12-04 16:25:00+08:00,2025-12-04 14:31:00+08:00
1,anmol,2025-12-04,16:25:00,2025-12-04,14:49:00,1,1,2025-12-04 16:25:00+08:00,2025-12-04 14:49:00+08:00
2,anmol,2025-12-04,16:25:00,2025-12-04,14:51:00,1,2,2025-12-04 16:25:00+08:00,2025-12-04 14:51:00+08:00
3,anmol,2025-12-04,16:25:00,2025-12-04,14:53:00,1,3,2025-12-04 16:25:00+08:00,2025-12-04 14:53:00+08:00
4,anmol,2025-12-04,16:25:00,2025-12-04,14:56:00,1,4,2025-12-04 16:25:00+08:00,2025-12-04 14:56:00+08:00

In [5]:
df_r_p = merge_df(df_records,df_pseudo)

    username                 lesson_at                       booking_at  \
0    ajithak 2025-08-28 18:50:00+08:00 2025-08-21 09:24:06.300383+08:00
1    ajithak 2025-08-28 20:40:00+08:00 2025-08-21 09:24:16.048708+08:00
2     addity 2025-09-21 14:35:00+08:00 2025-08-23 00:57:26.576198+08:00
3      bryan 2025-08-28 20:40:00+08:00 2025-08-25 12:06:06.539664+08:00
4      bryan 2025-08-31 12:45:00+08:00 2025-08-26 12:50:24.317931+08:00
..       ...                       ...                              ...
631        d 2025-11-07 18:50:00+08:00        2025-10-28 17:10:00+08:00
632    bhara 2025-11-03 16:25:00+08:00        2025-10-29 15:56:00+08:00
633    bhara 2025-11-03 16:25:00+08:00        2025-10-29 15:56:00+08:00
634    bhara 2025-11-04 18:50:00+08:00        2025-10-29 16:34:00+08:00
635    bhara 2025-11-04 18:50:00+08:00        2025-10-29 16:34:00+08:00

     booking_type class_type  is_one_team
0               0          3            0
1               0          3            0
2               0         3a            1
3               0         3a            0
4               0         3a            0
..            ...        ...          ...
631             1          3            0
632             1          3            0
633             1          3            0
634             1          3            0
635             1          3            0

[636 rows x 6 columns]
2026-05-06 20:33:59.491 | INFO     | cdc_ml.datasets.records_pseudo.records_pseudo:merge_df:102 - Total 524 rows x 5 columns

In [6]:
df_r_p

,id,username,lesson_at,booking_at,booking_type
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0
...,...,...,...,...,...
519,519,tomato,NaT,2026-01-01 00:01:00+08:00,1
520,520,bhara,2025-11-04 18:50:00+08:00,2025-10-28 13:53:00+08:00,1
521,521,d,2025-11-07 18:50:00+08:00,2025-10-28 17:10:00+08:00,1
522,522,bhara,2025-11-03 16:25:00+08:00,2025-10-29 15:56:00+08:00,1
523,523,bhara,2025-11-04 18:50:00+08:00,2025-10-29 16:34:00+08:00,1

In [7]:
df_class = pd.read_csv(RAW_DATA_DIR/"customer_class.csv")

In [8]:
df_class

      nickname                       course_type
0   Admin User             03. Class 3A Motorcar
1           Jj             03. Class 3A Motorcar
2            B             03. Class 3A Motorcar
3            G             03. Class 3A Motorcar
4     Shahtiya            CLASS 3 PRACTICAL TEST
..         ...                               ...
77      Flower             03. Class 3A Motorcar
78         Ali   02. Class 3 Motorcar (One Team)
79          yw  Simulator Course - Car (Private)
80      Amirul                 Class 2B lesson 4
81   Gᴜᴀɴ Sᴇɴɢ  Simulator Course - Car (Private)

[82 rows x 2 columns]

In [9]:
customers = df_r_p["username"].unique()

In [10]:
customers

<ArrowStringArray>
['ajithak',  'addity',   'bryan', 'lucinda',    'matt',    'sara',      'bw',
 'ranjith',    'srpr',     'fir', 'afellow',      'jy',   'carol',   'isyaf',
     'max',     'jun',     'kim',   'natar',     'mya',   'anaya',   'apple',
     'joy',    'ryan',     'nur',  'flower', 'brendon',  'tomato',   'anmol',
  'poopie',    'phuc', 'gohguan', 'pakning',      'np',     'ali',   'faith',
  'aswath',   'bhara',       'd']
Length: 38, dtype: str

In [11]:
df_class["nickname"] = df_class["nickname"].str.lower()

In [12]:
df_class["nickname"].unique()

<ArrowStringArray>
[       'admin user',                'jj',                 'b',
                 'g',          'shahtiya',                 'j',
                'gv',              'matt',              'srpr',
                 'x',            'yannis',             'carol',
               'ven',             'bhara',                 'd',
            'fluffy',            'yuhong',             'issac',
         'ryan wong',           'brandon',               'nur',
               'wxn',             'natar',              'zack',
                 'k',         'wrongnick',               'joy',
           'schwarz',               'gaj',           'brendon',
                'aj',               'guy',              'ryan',
              'phuc',             'ellen',           'gohguan',
                 's',             'anaya',                 'r',
            'addity',            'poopie',            'taslim',
               'val',              'ad_i',              'kobe',
           'pakning',             'apple',                'np',
               'jun',            'tomato',              'yong',
           'mxnxpxl',            'olivia',            'rajini',
               'zxt',   'zaydon 97228265',          'rarefish',
 'olivia (づ˶•༝•˶)づ♡',                ':)',             'faith',
             'anmol',           'kenneth',                'jy',
            'aswath',               'kim',               'pra',
               'mya',            'flower',               'ali',
                'yw',            'amirul',         'gᴜᴀɴ sᴇɴɢ']
Length: 72, dtype: str

In [13]:
temp = df_r_p.loc[~df_r_p["username"].isin(df_class["nickname"].unique()),"username"].unique()

In [14]:
temp

<ArrowStringArray>
['ajithak',   'bryan', 'lucinda',    'sara',      'bw', 'ranjith',     'fir',
 'afellow',   'isyaf',     'max']
Length: 10, dtype: str

In [15]:
main_customers = df_class.loc[df_class["nickname"].isin(df_r_p["username"].unique())].drop_duplicates()

In [16]:
main_customers

   nickname                        course_type
7      matt   04. Class 3A Motorcar (One Team)
8      srpr               01. Class 3 Motorcar
11    carol              03. Class 3A Motorcar
13    bhara               01. Class 3 Motorcar
15        d               01. Class 3 Motorcar
21      nur              03. Class 3A Motorcar
23    natar    02. Class 3 Motorcar (One Team)
28     matt   Simulator Course - Car (Private)
30      joy               01. Class 3 Motorcar
33  brendon  Warm-Up and Vehicle Rental (Auto)
36     ryan    02. Class 3 Motorcar (One Team)
37     phuc   04. Class 3A Motorcar (One Team)
39  gohguan              03. Class 3A Motorcar
41    anaya               01. Class 3 Motorcar
43   addity   04. Class 3A Motorcar (One Team)
44   poopie              03. Class 3A Motorcar
49  pakning   04. Class 3A Motorcar (One Team)
50    apple       01. Class 3 Motorcar (Kovan)
51       np              03. Class 3A Motorcar
52      jun              03. Class 3A Motorcar
53   tomato   04. Class 3A Motorcar (One Team)
67    faith   04. Class 3A Motorcar (One Team)
68    anmol              03. Class 3A Motorcar
70       jy               01. Class 3 Motorcar
71   aswath              03. Class 3A Motorcar
72      kim              03. Class 3A Motorcar
74      mya   04. Class 3A Motorcar (One Team)
75     ryan   Simulator Course - Car (Private)
77   flower              03. Class 3A Motorcar
78      ali    02. Class 3 Motorcar (One Team)

<ArrowStringArray>
['ajithak',   'bryan', 'lucinda',    'sara',      'bw', 'ranjith',     'fir',
 'afellow',   'isyaf',     'max']
Length: 10, dtype: str

In [17]:
cus_class_dic ={
    "ajithak":"01. Class 3 Motorcar",
    "bryan":"03. Class 3A Motorcar",
    "lucinda":"03. Class 3A Motorcar",
    "sara":"03. Class 3A Motorcar",
    "bw":"03. Class 3A Motorcar",
    "ranjith":"01. Class 3 Motorcar",
    "fir":"03. Class 3A Motorcar",
    "afellow":"03. Class 3A Motorcar",
    "isyaf":"03. Class 3A Motorcar",
    "max":"04. Class 3A Motorcar (One Team)"
    
}



rows = []
for t in temp:
    rows.append(
        {"nickname":t,
         "course_type":cus_class_dic[t]
         }

    )

main_customers = pd.concat([main_customers,pd.DataFrame(rows)],axis=0,ignore_index=True)

In [18]:
main_customers

   nickname                        course_type
0      matt   04. Class 3A Motorcar (One Team)
1      srpr               01. Class 3 Motorcar
2     carol              03. Class 3A Motorcar
3     bhara               01. Class 3 Motorcar
4         d               01. Class 3 Motorcar
5       nur              03. Class 3A Motorcar
6     natar    02. Class 3 Motorcar (One Team)
7      matt   Simulator Course - Car (Private)
8       joy               01. Class 3 Motorcar
9   brendon  Warm-Up and Vehicle Rental (Auto)
10     ryan    02. Class 3 Motorcar (One Team)
11     phuc   04. Class 3A Motorcar (One Team)
12  gohguan              03. Class 3A Motorcar
13    anaya               01. Class 3 Motorcar
14   addity   04. Class 3A Motorcar (One Team)
15   poopie              03. Class 3A Motorcar
16  pakning   04. Class 3A Motorcar (One Team)
17    apple       01. Class 3 Motorcar (Kovan)
18       np              03. Class 3A Motorcar
19      jun              03. Class 3A Motorcar
20   tomato   04. Class 3A Motorcar (One Team)
21    faith   04. Class 3A Motorcar (One Team)
22    anmol              03. Class 3A Motorcar
23       jy               01. Class 3 Motorcar
24   aswath              03. Class 3A Motorcar
25      kim              03. Class 3A Motorcar
26      mya   04. Class 3A Motorcar (One Team)
27     ryan   Simulator Course - Car (Private)
28   flower              03. Class 3A Motorcar
29      ali    02. Class 3 Motorcar (One Team)
30  ajithak               01. Class 3 Motorcar
31    bryan              03. Class 3A Motorcar
32  lucinda              03. Class 3A Motorcar
33     sara              03. Class 3A Motorcar
34       bw              03. Class 3A Motorcar
35  ranjith               01. Class 3 Motorcar
36      fir              03. Class 3A Motorcar
37  afellow              03. Class 3A Motorcar
38    isyaf              03. Class 3A Motorcar
39      max   04. Class 3A Motorcar (One Team)

In [19]:
main_customers["course_type"].unique()

<ArrowStringArray>
[ '04. Class 3A Motorcar (One Team)',              '01. Class 3 Motorcar',
             '03. Class 3A Motorcar',   '02. Class 3 Motorcar (One Team)',
  'Simulator Course - Car (Private)', 'Warm-Up and Vehicle Rental (Auto)',
      '01. Class 3 Motorcar (Kovan)']
Length: 7, dtype: str

In [20]:
main_customers = main_customers[~main_customers["course_type"].isin(['Simulator Course - Car (Private)', 'Warm-Up and Vehicle Rental (Auto)',])]

In [21]:
class_mapping = {
    "3a":['04. Class 3A Motorcar (One Team)', '03. Class 3A Motorcar'],
    "3":['01. Class 3 Motorcar','02. Class 3 Motorcar (One Team)','01. Class 3 Motorcar (Kovan)']


}
main_customers

   nickname                       course_type
0      matt  04. Class 3A Motorcar (One Team)
1      srpr              01. Class 3 Motorcar
2     carol             03. Class 3A Motorcar
3     bhara              01. Class 3 Motorcar
4         d              01. Class 3 Motorcar
5       nur             03. Class 3A Motorcar
6     natar   02. Class 3 Motorcar (One Team)
8       joy              01. Class 3 Motorcar
10     ryan   02. Class 3 Motorcar (One Team)
11     phuc  04. Class 3A Motorcar (One Team)
12  gohguan             03. Class 3A Motorcar
13    anaya              01. Class 3 Motorcar
14   addity  04. Class 3A Motorcar (One Team)
15   poopie             03. Class 3A Motorcar
16  pakning  04. Class 3A Motorcar (One Team)
17    apple      01. Class 3 Motorcar (Kovan)
18       np             03. Class 3A Motorcar
19      jun             03. Class 3A Motorcar
20   tomato  04. Class 3A Motorcar (One Team)
21    faith  04. Class 3A Motorcar (One Team)
22    anmol             03. Class 3A Motorcar
23       jy              01. Class 3 Motorcar
24   aswath             03. Class 3A Motorcar
25      kim             03. Class 3A Motorcar
26      mya  04. Class 3A Motorcar (One Team)
28   flower             03. Class 3A Motorcar
29      ali   02. Class 3 Motorcar (One Team)
30  ajithak              01. Class 3 Motorcar
31    bryan             03. Class 3A Motorcar
32  lucinda             03. Class 3A Motorcar
33     sara             03. Class 3A Motorcar
34       bw             03. Class 3A Motorcar
35  ranjith              01. Class 3 Motorcar
36      fir             03. Class 3A Motorcar
37  afellow             03. Class 3A Motorcar
38    isyaf             03. Class 3A Motorcar
39      max  04. Class 3A Motorcar (One Team)

In [22]:
main_customers["course_type"].unique()

<ArrowStringArray>
['04. Class 3A Motorcar (One Team)',             '01. Class 3 Motorcar',
            '03. Class 3A Motorcar',  '02. Class 3 Motorcar (One Team)',
     '01. Class 3 Motorcar (Kovan)']
Length: 5, dtype: str