In [1]:
import pandas as pd
from cdc_ml.config import EXTERNAL_DATA_DIR
from cdc_ml.datasets.constants import TIMEZONE
from cdc_ml.datasets.cycle.cycle import clean_df
import numpy as np

2026-05-07 15:03:17.820 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df = pd.read_excel(EXTERNAL_DATA_DIR/"booking_cycle.xlsx")

In [3]:
df.head()

,username,cycle start date,cycle start time,preference,range,cycle end date,cycle end time,cycle_end_reason
0,ajithak,2025-08-19,09:15:00,"monday to saturday after 5pm , sunday anytime",till next week,2025-08-21,11:00:00,completed
1,addity,2025-08-13,21:00:00,"weeday after 7 , no tues and thurs",before oct,2025-08-28,11:36:00,completed
2,addity,2025-10-16,00:00:00,"anytime on weekends , weekday after 630pm",26 oct to 14 dec,2025-10-17,20:00:00,completed
3,addity,2026-01-16,20:00:00,"friday and weekends anytime, other weekdays af...",Jan and feb,2026-01-19,00:00:00,completed
4,bryan,2025-08-22,00:48:00,"before 25 sept , weekday after 730pm , 12 pm o...",NaN,2025-09-05,16:00:00,completed

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   username          123 non-null    str
 1   cycle start date  123 non-null    datetime64[us]
 2   cycle start time  123 non-null    object
 3   preference        92 non-null     object
 4   range             83 non-null     object
 5   cycle end date    123 non-null    datetime64[us]
 6   cycle end time    123 non-null    object
 7   cycle_end_reason  107 non-null    str
dtypes: datetime64[us](2), object(4), str(2)
memory usage: 9.3+ KB

In [5]:
df = clean_df(df)

2026-05-07 15:03:18.140 | INFO     | cdc_ml.datasets.cycle.cycle:clean_df:53 - Pre cleaning:123 rows x 8 columns

In [6]:
df.head()

,username,preference,range,cycle_end_reason,cycle_start,cycle_end
0,ajithak,"monday to saturday after 5pm , sunday anytime",till next week,completed,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00
1,addity,"weeday after 7 , no tues and thurs",before oct,completed,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00
2,addity,"anytime on weekends , weekday after 630pm",26 oct to 14 dec,completed,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00
3,addity,"friday and weekends anytime, other weekdays af...",Jan and feb,completed,2026-01-16 20:00:00+08:00,2026-01-19 00:00:00+08:00
4,bryan,"before 25 sept , weekday after 730pm , 12 pm o...",NaN,completed,2025-08-22 00:48:00+08:00,2025-09-05 16:00:00+08:00

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   username          123 non-null    str
 1   preference        92 non-null     str
 2   range             83 non-null     str
 3   cycle_end_reason  107 non-null    str
 4   cycle_start       123 non-null    datetime64[ns, Asia/Singapore]
 5   cycle_end         123 non-null    datetime64[ns, Asia/Singapore]
dtypes: datetime64[ns, Asia/Singapore](2), str(4)
memory usage: 11.6 KB