In [16]:
import pandas as pd
from cdc_ml.datasets.merge.merge_complete_records_class import merge_df
from cdc_ml.config import INTERIM_COMPLETE_RECORDS_PARQUET,INTERIM_CLASS_PARQUET

In [17]:
df_records = pd.read_parquet(INTERIM_COMPLETE_RECORDS_PARQUET)
df_class = pd.read_parquet(INTERIM_CLASS_PARQUET)

In [18]:

df_records

,id,username,lesson_at,booking_at,booking_type
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0
...,...,...,...,...,...
519,519,tomato,NaT,2026-01-01 00:01:00+08:00,1
520,520,bhara,2025-11-04 18:50:00+08:00,2025-10-28 13:53:00+08:00,1
521,521,d,2025-11-07 18:50:00+08:00,2025-10-28 17:10:00+08:00,1
522,522,bhara,2025-11-03 16:25:00+08:00,2025-10-29 15:56:00+08:00,1
523,523,bhara,2025-11-04 18:50:00+08:00,2025-10-29 16:34:00+08:00,1

In [19]:
df_class

   username class_type  is_one_team
0      matt         3a            1
1      srpr          3            0
2     carol         3a            0
3     bhara          3            0
4     bhara          3            0
5         d          3            0
6       nur         3a            0
7     natar          3            1
8       joy          3            0
9      ryan          3            1
10     phuc         3a            1
11  gohguan         3a            0
12    anaya          3            0
13   addity         3a            1
14   poopie         3a            0
15  pakning         3a            1
16    apple          3            0
17       np         3a            0
18      jun         3a            0
19   tomato         3a            1
20    faith         3a            1
21    anmol         3a            0
22       jy          3            0
23   aswath         3a            0
24      kim         3a            0
25      mya         3a            1
26    anmol         3a            0
27   flower         3a            0
28      ali          3            1
29  ajithak          3            0
30  brendon         3a            0
31    bryan         3a            0
32  lucinda         3a            0
33     sara         3a            0
34       bw         3a            0
35  ranjith          3            0
36      fir         3a            0
37  afellow         3a            0
38    isyaf         3a            0
39      max         3a            1

In [20]:
df = merge_df(df_records,df_class)

In [21]:
df

,id,username,lesson_at,booking_at,booking_type,class_type,is_one_team
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0,3,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0,3,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0,3a,1
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0,3a,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0,3a,0
...,...,...,...,...,...,...,...
631,521,d,2025-11-07 18:50:00+08:00,2025-10-28 17:10:00+08:00,1,3,0
632,522,bhara,2025-11-03 16:25:00+08:00,2025-10-29 15:56:00+08:00,1,3,0
633,522,bhara,2025-11-03 16:25:00+08:00,2025-10-29 15:56:00+08:00,1,3,0
634,523,bhara,2025-11-04 18:50:00+08:00,2025-10-29 16:34:00+08:00,1,3,0
635,523,bhara,2025-11-04 18:50:00+08:00,2025-10-29 16:34:00+08:00,1,3,0