In [2]:
import pandas as pd
from cdc_ml.datasets.poll.poll import generate_df
from cdc_ml.config import BOOKING_CYCLES_PROCESSED,RECORDS_PROCESSED

2026-05-31 20:12:42.140 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [3]:
df_cycle = pd.read_parquet(BOOKING_CYCLES_PROCESSED)
df_records = pd.read_parquet(RECORDS_PROCESSED)

In [4]:
df = generate_df(df_cycle,df_records)

2026-05-31 20:12:43.038 | INFO     | cdc_ml.datasets.poll.poll:validate_booking_records:55 - All booking records are validated against booking cycle...

In [5]:
df.head()

,id,cycle_id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
0,0,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 09:00:00+08:00,False,8,19,1,9,8,19,1,9,-0.25
1,1,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 10:00:00+08:00,False,8,19,1,9,8,19,1,10,0.75
2,2,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 11:00:00+08:00,False,8,19,1,9,8,19,1,11,1.75
3,3,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 12:00:00+08:00,False,8,19,1,9,8,19,1,12,2.75
4,4,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 13:00:00+08:00,False,8,19,1,9,8,19,1,13,3.75

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32492 entries, 0 to 32491
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 32492 non-null  int64
 1   cycle_id           32492 non-null  int64
 2   username           32492 non-null  str
 3   cycle_start        32492 non-null  datetime64[us, Asia/Singapore]
 4   cycle_end          32492 non-null  datetime64[us, Asia/Singapore]
 5   polling_at         32492 non-null  datetime64[us, Asia/Singapore]
 6   has_booking        32492 non-null  bool
 7   cycle_start_month  32492 non-null  int32
 8   cycle_start_day    32492 non-null  int32
 9   cycle_start_dow    32492 non-null  int32
 10  cycle_start_hour   32492 non-null  int32
 11  polling_month      32492 non-null  int32
 12  polling_day        32492 non-null  int32
 13  polling_dow        32492 non-null  int32
 14  polling_hour       32492 non-null  int32
 15  hours_into_cycle   32492 non-null  float64
dtypes: bool(1), datetime64[us, Asia/Singapore](3), float64(1), int32(8), int64(2), str(1)
memory usage: 2.9 MB

In [7]:
df["username"].unique()

<ArrowStringArray>
['ajithak',  'addity',   'bryan', 'lucinda',    'matt', 'ranjith',    'srpr',
      'jy',    'sara',      'bw',     'fir', 'brendon',   'carol',   'isyaf',
     'max',     'jun',     'kim',   'natar',     'mya',   'apple',     'joy',
    'ryan',     'nur',  'flower',  'tomato',   'anmol',  'poopie',    'phuc',
 'gohguan', 'pakning',      'np',   'faith',  'aswath',   'anaya',     'ali',
   'bhara',       'd']
Length: 37, dtype: str

In [8]:
df.loc[df["has_booking"]==1]

,id,cycle_id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
48,48,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-21 09:00:00+08:00,True,8,19,1,9,8,21,3,9,47.75
269,269,1,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-23 00:00:00+08:00,True,8,13,2,21,8,23,5,0,219.00
395,395,1,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-28 06:00:00+08:00,True,8,13,2,21,8,28,3,6,345.00
419,419,2,addity,2025-10-17 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,True,10,17,4,0,10,17,4,18,18.00
559,559,4,bryan,2025-08-22 00:48:00+08:00,2025-09-05 16:00:00+08:00,2025-08-25 12:00:00+08:00,True,8,22,4,0,8,25,0,12,83.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32150,32150,119,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-29 15:00:00+08:00,True,10,25,5,0,10,29,2,15,111.00
32151,32151,119,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-29 16:00:00+08:00,True,10,25,5,0,10,29,2,16,112.00
32272,32272,120,d,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00,2025-10-28 17:00:00+08:00,True,10,25,5,0,10,28,1,17,89.00
32470,32470,121,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-16 23:00:00+08:00,True,10,16,3,0,10,16,3,23,23.00
32489,32489,121,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,True,10,16,3,0,10,17,4,18,42.00

In [9]:
df.sample()

,id,cycle_id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
23898,23898,92,anmol,2026-02-04 12:57:00+08:00,2026-02-14 23:59:00+08:00,2026-02-04 19:00:00+08:00,False,2,4,2,12,2,4,2,19,6.05

In [10]:
df = df.assign(floored=df["polling_at"].dt.floor("h"))
test = df.groupby("floored")["username"].nunique().sort_values(ascending=False)
print(test)
print(len(test))
print(test.mean())


print(df.loc[df["floored"]=="2025-11-27 17:00:00+08:00"]["username"])

floored
2025-11-27 17:00:00+08:00    12
2025-11-27 19:00:00+08:00    12
2025-11-27 18:00:00+08:00    12
2025-11-27 21:00:00+08:00    12
2025-11-27 22:00:00+08:00    12
                             ..
2025-08-12 05:00:00+08:00     1
2025-08-12 06:00:00+08:00     1
2025-08-12 09:00:00+08:00     1
2026-04-26 00:00:00+08:00     1
2026-04-26 17:00:00+08:00     1
Name: username, Length: 5975, dtype: int64
5975
5.344602510460251
5000          jy
8130     brendon
9527         jun
11272        kim
14272      natar
14976        mya
17420        joy
18103       ryan
20038     flower
22068     tomato
26122    gohguan
29450      anaya
Name: username, dtype: str

In [11]:
df.groupby(['polling_dow','polling_hour'])['has_booking'].sum().value_counts()

has_booking
0     55
1     38
3     16
2     15
5     12
4      8
7      6
6      6
9      5
8      4
11     1
12     1
10     1
Name: count, dtype: int64

In [12]:
print(len(df.loc[df["has_booking"]==1]))

396

In [13]:
df.groupby(['username','polling_month','polling_day','polling_hour']) \
  ['has_booking'].sum().value_counts()

has_booking
0    31547
1      378
2        9
Name: count, dtype: int64

In [14]:
test2 = df.groupby(["polling_month","polling_day","polling_hour"])["username"].count()
print(test2)
print(test2.mean())

polling_month  polling_day  polling_hour
1              1            0               10
                            1               10
                            2               10
                            3               10
                            4               10
                                            ..
12             31           19              10
                            20              10
                            21              10
                            22              10
                            23              10
Name: username, Length: 5975, dtype: int64
5.4379916317991635

In [15]:
df.loc[df["username"]=="addity"]

,id,cycle_id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle,floored
50,50,1,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-13 21:00:00+08:00,False,8,13,2,21,8,13,2,21,0.0,2025-08-13 21:00:00+08:00
51,51,1,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-13 22:00:00+08:00,False,8,13,2,21,8,13,2,22,1.0,2025-08-13 22:00:00+08:00
52,52,1,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-13 23:00:00+08:00,False,8,13,2,21,8,13,2,23,2.0,2025-08-13 23:00:00+08:00
53,53,1,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-14 00:00:00+08:00,False,8,13,2,21,8,14,3,0,3.0,2025-08-14 00:00:00+08:00
54,54,1,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-14 01:00:00+08:00,False,8,13,2,21,8,14,3,1,4.0,2025-08-14 01:00:00+08:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32487,32487,121,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 16:00:00+08:00,False,10,16,3,0,10,17,4,16,40.0,2025-10-17 16:00:00+08:00
32488,32488,121,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 17:00:00+08:00,False,10,16,3,0,10,17,4,17,41.0,2025-10-17 17:00:00+08:00
32489,32489,121,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,True,10,16,3,0,10,17,4,18,42.0,2025-10-17 18:00:00+08:00
32490,32490,121,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 19:00:00+08:00,False,10,16,3,0,10,17,4,19,43.0,2025-10-17 19:00:00+08:00
32491,32491,121,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 20:00:00+08:00,False,10,16,3,0,10,17,4,20,44.0,2025-10-17 20:00:00+08:00

In [16]:
df.loc[(df["username"]=="poopie")& (df["has_booking"]==1)]

,id,cycle_id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle,floored
25249,25249,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-22 10:00:00+08:00,True,12,18,3,10,12,22,0,10,95.166667,2025-12-22 10:00:00+08:00
25253,25253,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-22 14:00:00+08:00,True,12,18,3,10,12,22,0,14,99.166667,2025-12-22 14:00:00+08:00
25254,25254,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-22 15:00:00+08:00,True,12,18,3,10,12,22,0,15,100.166667,2025-12-22 15:00:00+08:00
25255,25255,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-22 16:00:00+08:00,True,12,18,3,10,12,22,0,16,101.166667,2025-12-22 16:00:00+08:00
25257,25257,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-22 18:00:00+08:00,True,12,18,3,10,12,22,0,18,103.166667,2025-12-22 18:00:00+08:00
25271,25271,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-23 08:00:00+08:00,True,12,18,3,10,12,23,1,8,117.166667,2025-12-23 08:00:00+08:00
25275,25275,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-23 12:00:00+08:00,True,12,18,3,10,12,23,1,12,121.166667,2025-12-23 12:00:00+08:00
25276,25276,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-23 13:00:00+08:00,True,12,18,3,10,12,23,1,13,122.166667,2025-12-23 13:00:00+08:00
25278,25278,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-23 15:00:00+08:00,True,12,18,3,10,12,23,1,15,124.166667,2025-12-23 15:00:00+08:00
25281,25281,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-23 18:00:00+08:00,True,12,18,3,10,12,23,1,18,127.166667,2025-12-23 18:00:00+08:00
25299,25299,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-24 12:00:00+08:00,True,12,18,3,10,12,24,2,12,145.166667,2025-12-24 12:00:00+08:00
25350,25350,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-26 15:00:00+08:00,True,12,18,3,10,12,26,4,15,196.166667,2025-12-26 15:00:00+08:00
25366,25366,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-27 07:00:00+08:00,True,12,18,3,10,12,27,5,7,212.166667,2025-12-27 07:00:00+08:00
25369,25369,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-27 10:00:00+08:00,True,12,18,3,10,12,27,5,10,215.166667,2025-12-27 10:00:00+08:00
25391,25391,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-28 08:00:00+08:00,True,12,18,3,10,12,28,6,8,237.166667,2025-12-28 08:00:00+08:00
25422,25422,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-29 15:00:00+08:00,True,12,18,3,10,12,29,0,15,268.166667,2025-12-29 15:00:00+08:00
25444,25444,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2025-12-30 13:00:00+08:00,True,12,18,3,10,12,30,1,13,290.166667,2025-12-30 13:00:00+08:00
25517,25517,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-02 14:00:00+08:00,True,12,18,3,10,1,2,4,14,363.166667,2026-01-02 14:00:00+08:00
25539,25539,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-03 12:00:00+08:00,True,12,18,3,10,1,3,5,12,385.166667,2026-01-03 12:00:00+08:00
25610,25610,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-06 11:00:00+08:00,True,12,18,3,10,1,6,1,11,456.166667,2026-01-06 11:00:00+08:00
25614,25614,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-06 15:00:00+08:00,True,12,18,3,10,1,6,1,15,460.166667,2026-01-06 15:00:00+08:00
25616,25616,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-06 17:00:00+08:00,True,12,18,3,10,1,6,1,17,462.166667,2026-01-06 17:00:00+08:00
25632,25632,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-07 09:00:00+08:00,True,12,18,3,10,1,7,2,9,478.166667,2026-01-07 09:00:00+08:00
25633,25633,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-07 10:00:00+08:00,True,12,18,3,10,1,7,2,10,479.166667,2026-01-07 10:00:00+08:00
25637,25637,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-07 14:00:00+08:00,True,12,18,3,10,1,7,2,14,483.166667,2026-01-07 14:00:00+08:00
25638,25638,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-07 15:00:00+08:00,True,12,18,3,10,1,7,2,15,484.166667,2026-01-07 15:00:00+08:00
25658,25658,96,poopie,2025-12-18 10:50:00+08:00,2026-01-08 23:59:00+08:00,2026-01-08 11:00:00+08:00,True,12,18,3,10,1,8,3,11,504.166667,2026-01-08 11:00:00+08:00
25733,25733,97,poopie,2026-01-10 00:00:00+08:00,2026-01-19 23:59:00+08:00,2026-01-12 14:00:00+08:00,True,1,10,5,0,1,12,0,14,62.000000,2026-01-12 14:00:00+08:00
25743,25743,97,poopie,2026-01-10 00:00:00+08:00,2026-01-19 23:59:00+08:00,2026-01-13 00:00:00+08:00,True,1,10,5,0,1,13,1,0,72.000000,2026-01-13 00:00:00+08:00
25854,25854,97,poopie,2026-01-10 00:00:00+08:00,2026-01-19 23:59:00+08:00,2026-01-17 15:00:00+08:00,True,1,10,5,0,1,17,5,15,183.000000,2026-01-17 15:00:00+08:00
25896,25896,97,poopie,2026-01-10 00:00:00+08:00,2026-01-19 23:59:00+08:00,2026-01-19 09:00:00+08:00,True,1,10,5,0,1,19,0,9,225.000000,2026-01-19 09:00:00+08:00