In [1]:
import pandas as pd 
from cdc_ml.features.build_features import build_features
from cdc_ml.config import INTERIM_DATA_DIR,PROCESSED_DATA_DIR

2026-05-06 15:06:25.941 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_cycle = pd.read_parquet(INTERIM_DATA_DIR/"cycle.parquet")
df_records = pd.read_parquet(INTERIM_DATA_DIR/"refined_records.parquet")

In [3]:
df_cycle

,username,preference,range,cycle_end_reason,cycle_start,cycle_end
0,ajithak,"monday to saturday after 5pm , sunday anytime",till next week,completed,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00
1,addity,"weeday after 7 , no tues and thurs",before oct,completed,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00
2,addity,"anytime on weekends , weekday after 630pm",26 oct to 14 dec,completed,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00
3,addity,"friday and weekends anytime, other weekdays af...",Jan and feb,completed,2026-01-16 20:00:00+08:00,2026-01-19 00:00:00+08:00
4,bryan,"before 25 sept , weekday after 730pm , 12 pm o...",NaN,completed,2025-08-22 00:48:00+08:00,2025-09-05 16:00:00+08:00
...,...,...,...,...,...,...
118,ali,whoe march anytime,NaN,NaN,2026-03-02 00:00:00+08:00,2026-03-24 23:59:00+08:00
119,ali,whole apr anytime,NaN,NaN,2026-03-25 00:00:00+08:00,2026-04-10 23:59:00+08:00
120,ali,whole apr anytime,NaN,NaN,2026-04-21 00:00:00+08:00,2026-04-25 23:59:00+08:00
121,bhara,"slot 5,6,7 all day 25 oct to 30 nov",NaN,NaN,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00
122,d,"27 oct to 31 dec , 6,7",NaN,NaN,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00

In [4]:
df_records

,id,username,lesson_at,booking_at,booking_type
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0
...,...,...,...,...,...
519,519,tomato,NaT,2026-01-01 00:01:00+08:00,1
520,520,bhara,2025-11-04 18:50:00+08:00,2025-10-28 13:53:00+08:00,1
521,521,d,2025-11-07 18:50:00+08:00,2025-10-28 17:10:00+08:00,1
522,522,bhara,2025-11-03 16:25:00+08:00,2025-10-29 15:56:00+08:00,1
523,523,bhara,2025-11-04 18:50:00+08:00,2025-10-29 16:34:00+08:00,1

In [5]:
df = build_features(df_cycle,df_records)

2026-05-06 15:06:26.383 | INFO     | cdc_ml.features.build_features:validate_booking_records:50 - All booking records are validated against booking cycle...
2026-05-06 15:06:26.455 | INFO     | cdc_ml.features.build_features:build_features:87 - Built new dataframe with 32636 rows x 6

In [6]:
df.head()

,id,username,cycle_start,cycle_end,polling_hour,has_booking
0,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 09:15:00+08:00,0
1,1,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 10:15:00+08:00,0
2,2,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 11:15:00+08:00,0
3,3,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 12:15:00+08:00,0
4,4,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 13:15:00+08:00,0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32636 entries, 0 to 32635
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            32636 non-null  int64
 1   username      32636 non-null  str
 2   cycle_start   32636 non-null  datetime64[ns, Asia/Singapore]
 3   cycle_end     32636 non-null  datetime64[ns, Asia/Singapore]
 4   polling_hour  32636 non-null  datetime64[ns, Asia/Singapore]
 5   has_booking   32636 non-null  int64
dtypes: datetime64[ns, Asia/Singapore](3), int64(2), str(1)
memory usage: 1.6 MB

In [8]:
df[df["has_booking"]==1]

,id,username,cycle_start,cycle_end,polling_hour,has_booking
48,48,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-21 09:15:00+08:00,1
269,269,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-23 00:00:00+08:00,1
395,395,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-28 06:00:00+08:00,1
424,424,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-16 23:00:00+08:00,1
443,443,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,1
...,...,...,...,...,...,...
32193,32193,ali,2026-04-21 00:00:00+08:00,2026-04-25 23:59:00+08:00,2026-04-24 13:00:00+08:00,1
32313,32313,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-28 13:00:00+08:00,1
32339,32339,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-29 15:00:00+08:00,1
32340,32340,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-29 16:00:00+08:00,1
32461,32461,d,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00,2025-10-28 17:00:00+08:00,1