In [21]:

import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold,GroupKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import brier_score_loss, average_precision_score
from cdc_ml.config import POLLS_PROCESSED,PREFERENCE_PROCESSED

In [22]:
df= pd.read_parquet(POLLS_PROCESSED)

In [23]:
df_1 = df.iloc[:10]
df_2 = df.iloc[10:20]

In [24]:
df_1

,id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
0,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 09:00:00+08:00,False,8,19,1,9,8,19,1,9,-0.25
1,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 10:00:00+08:00,False,8,19,1,9,8,19,1,10,0.75
2,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 11:00:00+08:00,False,8,19,1,9,8,19,1,11,1.75
3,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 12:00:00+08:00,False,8,19,1,9,8,19,1,12,2.75
4,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 13:00:00+08:00,False,8,19,1,9,8,19,1,13,3.75
5,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 14:00:00+08:00,False,8,19,1,9,8,19,1,14,4.75
6,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 15:00:00+08:00,False,8,19,1,9,8,19,1,15,5.75
7,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 16:00:00+08:00,False,8,19,1,9,8,19,1,16,6.75
8,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 17:00:00+08:00,False,8,19,1,9,8,19,1,17,7.75
9,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 18:00:00+08:00,False,8,19,1,9,8,19,1,18,8.75

In [25]:
df_2

,id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
10,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 19:00:00+08:00,False,8,19,1,9,8,19,1,19,9.75
11,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 20:00:00+08:00,False,8,19,1,9,8,19,1,20,10.75
12,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 21:00:00+08:00,False,8,19,1,9,8,19,1,21,11.75
13,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 22:00:00+08:00,False,8,19,1,9,8,19,1,22,12.75
14,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 23:00:00+08:00,False,8,19,1,9,8,19,1,23,13.75
15,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 00:00:00+08:00,False,8,19,1,9,8,20,2,0,14.75
16,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 01:00:00+08:00,False,8,19,1,9,8,20,2,1,15.75
17,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 02:00:00+08:00,False,8,19,1,9,8,20,2,2,16.75
18,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 03:00:00+08:00,False,8,19,1,9,8,20,2,3,17.75
19,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 04:00:00+08:00,False,8,19,1,9,8,20,2,4,18.75

In [26]:
x = df_1["has_booking"].to_numpy()

In [27]:
x

array([False, False, False, False, False, False, False, False, False,
       False])

In [28]:
test = pd.concat([df_2,pd.Series(x)],axis=1)

In [29]:
test

,id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle,0
10,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 19:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,19.0,1.0,19.0,9.75,NaN
11,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 20:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,19.0,1.0,20.0,10.75,NaN
12,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 21:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,19.0,1.0,21.0,11.75,NaN
13,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 22:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,19.0,1.0,22.0,12.75,NaN
14,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 23:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,19.0,1.0,23.0,13.75,NaN
15,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 00:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,20.0,2.0,0.0,14.75,NaN
16,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 01:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,20.0,2.0,1.0,15.75,NaN
17,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 02:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,20.0,2.0,2.0,16.75,NaN
18,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 03:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,20.0,2.0,3.0,17.75,NaN
19,0.0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-20 04:00:00+08:00,False,8.0,19.0,1.0,9.0,8.0,20.0,2.0,4.0,18.75,NaN
0,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
6,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
7,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
8,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
9,NaN,NaN,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False